// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	User
	CreateAccountReq
	CreateAccountResp
	UserPrompt
	Prompt
	Communication
	Journal
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Birthday    string `protobuf:"bytes,4,opt,name=birthday" json:"birthday,omitempty"`
	Verified    bool   `protobuf:"varint,5,opt,name=verified" json:"verified,omitempty"`
	SessionId   string `protobuf:"bytes,6,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CreateAccountReq struct {
	User           *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	PasswordRepeat string `protobuf:"bytes,2,opt,name=password_repeat,json=passwordRepeat" json:"password_repeat,omitempty"`
}

func (m *CreateAccountReq) Reset()                    { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()               {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAccountReq) GetPasswordRepeat() string {
	if m != nil {
		return m.PasswordRepeat
	}
	return ""
}

type CreateAccountResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CreateAccountResp) Reset()                    { *m = CreateAccountResp{} }
func (m *CreateAccountResp) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResp) ProtoMessage()               {}
func (*CreateAccountResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateAccountResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserPrompt struct {
	PromptId       string  `protobuf:"bytes,1,opt,name=prompt_id,json=promptId" json:"prompt_id,omitempty"`
	PhoneNumber    string  `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	NextPromptTime string  `protobuf:"bytes,3,opt,name=next_prompt_time,json=nextPromptTime" json:"next_prompt_time,omitempty"`
	Frequency      string  `protobuf:"bytes,4,opt,name=frequency" json:"frequency,omitempty"`
	Prompt         *Prompt `protobuf:"bytes,5,opt,name=prompt" json:"prompt,omitempty"`
}

func (m *UserPrompt) Reset()                    { *m = UserPrompt{} }
func (m *UserPrompt) String() string            { return proto.CompactTextString(m) }
func (*UserPrompt) ProtoMessage()               {}
func (*UserPrompt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserPrompt) GetPromptId() string {
	if m != nil {
		return m.PromptId
	}
	return ""
}

func (m *UserPrompt) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserPrompt) GetNextPromptTime() string {
	if m != nil {
		return m.NextPromptTime
	}
	return ""
}

func (m *UserPrompt) GetFrequency() string {
	if m != nil {
		return m.Frequency
	}
	return ""
}

func (m *UserPrompt) GetPrompt() *Prompt {
	if m != nil {
		return m.Prompt
	}
	return nil
}

type Prompt struct {
	PromptId string `protobuf:"bytes,1,opt,name=prompt_id,json=promptId" json:"prompt_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Template string `protobuf:"bytes,4,opt,name=template" json:"template,omitempty"`
}

func (m *Prompt) Reset()                    { *m = Prompt{} }
func (m *Prompt) String() string            { return proto.CompactTextString(m) }
func (*Prompt) ProtoMessage()               {}
func (*Prompt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Prompt) GetPromptId() string {
	if m != nil {
		return m.PromptId
	}
	return ""
}

func (m *Prompt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Prompt) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Prompt) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type Communication struct {
	CommsId string `protobuf:"bytes,1,opt,name=comms_id,json=commsId" json:"comms_id,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To      string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *Communication) Reset()                    { *m = Communication{} }
func (m *Communication) String() string            { return proto.CompactTextString(m) }
func (*Communication) ProtoMessage()               {}
func (*Communication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Communication) GetCommsId() string {
	if m != nil {
		return m.CommsId
	}
	return ""
}

func (m *Communication) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Communication) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Communication) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Journal struct {
	JournalId   string `protobuf:"bytes,1,opt,name=journal_id,json=journalId" json:"journal_id,omitempty"`
	CommsId     string `protobuf:"bytes,2,opt,name=comms_id,json=commsId" json:"comms_id,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Prompt      string `protobuf:"bytes,4,opt,name=prompt" json:"prompt,omitempty"`
	Entry       string `protobuf:"bytes,5,opt,name=entry" json:"entry,omitempty"`
	Created     string `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
	Updated     string `protobuf:"bytes,7,opt,name=updated" json:"updated,omitempty"`
}

func (m *Journal) Reset()                    { *m = Journal{} }
func (m *Journal) String() string            { return proto.CompactTextString(m) }
func (*Journal) ProtoMessage()               {}
func (*Journal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Journal) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *Journal) GetCommsId() string {
	if m != nil {
		return m.CommsId
	}
	return ""
}

func (m *Journal) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Journal) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *Journal) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *Journal) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Journal) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "notify.User")
	proto.RegisterType((*CreateAccountReq)(nil), "notify.CreateAccountReq")
	proto.RegisterType((*CreateAccountResp)(nil), "notify.CreateAccountResp")
	proto.RegisterType((*UserPrompt)(nil), "notify.UserPrompt")
	proto.RegisterType((*Prompt)(nil), "notify.Prompt")
	proto.RegisterType((*Communication)(nil), "notify.Communication")
	proto.RegisterType((*Journal)(nil), "notify.Journal")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0xdd, 0xd4, 0x89, 0x6f, 0x9a, 0x7c, 0xfd, 0x46, 0x55, 0xe5, 0x06, 0x90, 0x8a, 0x17,
	0xd0, 0x0d, 0x59, 0x94, 0x25, 0xab, 0x52, 0x40, 0x2a, 0x8b, 0x0a, 0x59, 0x65, 0x83, 0x84, 0x22,
	0xc7, 0xbe, 0x49, 0x07, 0x75, 0x7e, 0x3a, 0x33, 0x2e, 0xe4, 0xad, 0x78, 0x00, 0x1e, 0x80, 0x27,
	0xe0, 0x79, 0xd0, 0xfc, 0xa5, 0x7f, 0x8a, 0xc4, 0xee, 0x9e, 0x73, 0xc7, 0xf7, 0xde, 0x39, 0xe7,
	0x7a, 0x60, 0xa4, 0x51, 0xdd, 0xd0, 0x06, 0xa7, 0x52, 0x09, 0x23, 0x48, 0xc6, 0x85, 0xa1, 0x8b,
	0xd5, 0x64, 0x88, 0x4c, 0x9a, 0x95, 0x27, 0xcb, 0x9f, 0x09, 0xf4, 0x3e, 0x6b, 0x54, 0xe4, 0x39,
	0xec, 0xc8, 0x4b, 0xc1, 0x71, 0xc6, 0x3b, 0x36, 0x47, 0x55, 0x24, 0x87, 0xc9, 0x51, 0x5e, 0x0d,
	0x1d, 0x77, 0xee, 0x28, 0x32, 0x81, 0x81, 0xac, 0xb5, 0xfe, 0x2e, 0x54, 0x5b, 0xa4, 0x2e, 0xbd,
	0xc6, 0x84, 0x40, 0x8f, 0xd7, 0x0c, 0x8b, 0x2d, 0xc7, 0xbb, 0xd8, 0x9e, 0x9f, 0x53, 0x65, 0x2e,
	0xdb, 0x7a, 0x55, 0xf4, 0xfc, 0xf9, 0x88, 0x6d, 0xee, 0x06, 0x15, 0x5d, 0x50, 0x6c, 0x8b, 0xed,
	0xc3, 0xe4, 0x68, 0x50, 0xad, 0x31, 0x79, 0x06, 0xa0, 0x51, 0x6b, 0x2a, 0xf8, 0x8c, 0xb6, 0x45,
	0xe6, 0xbe, 0xcc, 0x03, 0x73, 0xd6, 0x96, 0x5f, 0x61, 0xf7, 0x54, 0x61, 0x6d, 0xf0, 0xa4, 0x69,
	0x44, 0xc7, 0x4d, 0x85, 0xd7, 0xe4, 0x10, 0x7a, 0x9d, 0x0e, 0x53, 0x0f, 0x8f, 0x77, 0xa6, 0xfe,
	0xaa, 0x53, 0x7b, 0xb3, 0xca, 0x65, 0xc8, 0x4b, 0xf8, 0x2f, 0x0e, 0x3b, 0x53, 0x28, 0xb1, 0x36,
	0xe1, 0x0e, 0xe3, 0x48, 0x57, 0x8e, 0x2d, 0x5f, 0xc1, 0xff, 0x0f, 0xca, 0x6b, 0x49, 0x0a, 0xe8,
	0xeb, 0xae, 0x69, 0x50, 0x6b, 0xd7, 0x62, 0x50, 0x45, 0x58, 0xfe, 0x4a, 0x00, 0x6c, 0x9b, 0x4f,
	0x4a, 0x30, 0x69, 0xc8, 0x13, 0xc8, 0xa5, 0x8b, 0xec, 0xe8, 0x49, 0x10, 0xc9, 0x11, 0x67, 0xed,
	0x23, 0x8d, 0xd3, 0xc7, 0x1a, 0x1f, 0xc1, 0x2e, 0xc7, 0x1f, 0x66, 0x16, 0x8a, 0x18, 0xba, 0xd6,
	0x74, 0x6c, 0x79, 0xdf, 0xe5, 0x82, 0x32, 0x24, 0x4f, 0x21, 0x5f, 0x28, 0xbc, 0xee, 0x90, 0x37,
	0x51, 0xde, 0x5b, 0x82, 0xbc, 0x80, 0xcc, 0x97, 0x70, 0xea, 0x0e, 0x8f, 0xc7, 0x51, 0x12, 0x5f,
	0xa1, 0x0a, 0xd9, 0x92, 0x42, 0xf6, 0x2f, 0x93, 0x47, 0x7b, 0xd3, 0x3b, 0xf6, 0x12, 0xe8, 0x99,
	0x95, 0x5c, 0x5b, 0x6e, 0x63, 0x6b, 0xab, 0x41, 0x26, 0xaf, 0x6a, 0x83, 0xd1, 0xf2, 0x88, 0xcb,
	0x4b, 0x18, 0x9d, 0x0a, 0xc6, 0x3a, 0x4e, 0x9b, 0xda, 0x50, 0xc1, 0xc9, 0x01, 0x0c, 0x1a, 0xc1,
	0x98, 0xbe, 0x6d, 0xd8, 0x77, 0xd8, 0xf7, 0x5b, 0x28, 0xc1, 0x62, 0x3f, 0x1b, 0x93, 0x31, 0xa4,
	0x46, 0x84, 0x6e, 0xa9, 0x11, 0xd6, 0x13, 0x86, 0x5a, 0xd7, 0xcb, 0xd8, 0x2a, 0xc2, 0xf2, 0x77,
	0x02, 0xfd, 0x8f, 0xa2, 0x53, 0xbc, 0xbe, 0xb2, 0xcb, 0xf4, 0xcd, 0x87, 0xb7, 0x6d, 0xf2, 0xc0,
	0x9c, 0xb5, 0xf7, 0x66, 0x48, 0xef, 0xcf, 0xf0, 0xd0, 0xad, 0xad, 0xc7, 0x6e, 0xed, 0xaf, 0x55,
	0xf6, 0x13, 0x04, 0x44, 0xf6, 0x60, 0x1b, 0xb9, 0x51, 0x2b, 0x27, 0x7e, 0x5e, 0x79, 0x60, 0x07,
	0x6e, 0xdc, 0x66, 0xc5, 0xa5, 0x8e, 0xd0, 0x66, 0x3a, 0xd9, 0xba, 0x4c, 0xdf, 0x67, 0x02, 0x3c,
	0xfe, 0x93, 0x40, 0x7e, 0xee, 0x9c, 0x3b, 0x91, 0x92, 0xbc, 0x83, 0xd1, 0xbd, 0xdd, 0x24, 0x45,
	0xb4, 0xf5, 0xe1, 0x1f, 0x31, 0x39, 0xd8, 0x90, 0xd1, 0x92, 0xbc, 0x81, 0xd1, 0x49, 0xdb, 0xde,
	0x59, 0x5a, 0x72, 0xf7, 0x7f, 0xf1, 0xdc, 0x64, 0x7f, 0xba, 0x14, 0x62, 0x79, 0x15, 0x1e, 0x8f,
	0x79, 0xb7, 0x98, 0xbe, 0xb7, 0xcf, 0x06, 0xf9, 0x00, 0x7b, 0x17, 0x8a, 0x2e, 0x97, 0xa8, 0xdc,
	0x58, 0xc1, 0x4b, 0x4d, 0x36, 0x9c, 0xdf, 0x54, 0xe7, 0xed, 0xe0, 0x4b, 0x66, 0x9f, 0x27, 0x54,
	0xf3, 0xcc, 0x65, 0x5e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xca, 0x3e, 0x46, 0x50, 0xaf, 0x04,
	0x00, 0x00,
}
