// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	User
	CreateAccountReq
	CreateAccountResp
	UserNotification
	Notification
	Communication
	Journal
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Birthday    string `protobuf:"bytes,4,opt,name=birthday" json:"birthday,omitempty"`
	Verified    bool   `protobuf:"varint,5,opt,name=verified" json:"verified,omitempty"`
	SessionId   string `protobuf:"bytes,6,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CreateAccountReq struct {
	User           *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	PasswordRepeat string `protobuf:"bytes,2,opt,name=password_repeat,json=passwordRepeat" json:"password_repeat,omitempty"`
}

func (m *CreateAccountReq) Reset()                    { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()               {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAccountReq) GetPasswordRepeat() string {
	if m != nil {
		return m.PasswordRepeat
	}
	return ""
}

type CreateAccountResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CreateAccountResp) Reset()                    { *m = CreateAccountResp{} }
func (m *CreateAccountResp) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResp) ProtoMessage()               {}
func (*CreateAccountResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateAccountResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserNotification struct {
	NotificationId       string        `protobuf:"bytes,1,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
	PhoneNumber          string        `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	NextNotificationTime string        `protobuf:"bytes,3,opt,name=next_notification_time,json=nextNotificationTime" json:"next_notification_time,omitempty"`
	Frequency            string        `protobuf:"bytes,4,opt,name=frequency" json:"frequency,omitempty"`
	Notification         *Notification `protobuf:"bytes,5,opt,name=notification" json:"notification,omitempty"`
}

func (m *UserNotification) Reset()                    { *m = UserNotification{} }
func (m *UserNotification) String() string            { return proto.CompactTextString(m) }
func (*UserNotification) ProtoMessage()               {}
func (*UserNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserNotification) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

func (m *UserNotification) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserNotification) GetNextNotificationTime() string {
	if m != nil {
		return m.NextNotificationTime
	}
	return ""
}

func (m *UserNotification) GetFrequency() string {
	if m != nil {
		return m.Frequency
	}
	return ""
}

func (m *UserNotification) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type Notification struct {
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type           string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Template       string `protobuf:"bytes,4,opt,name=template" json:"template,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Notification) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

func (m *Notification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Notification) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Notification) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type Communication struct {
	CommsId        string `protobuf:"bytes,1,opt,name=comms_id,json=commsId" json:"comms_id,omitempty"`
	From           string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To             string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Message        string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	NotificationId string `protobuf:"bytes,5,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
}

func (m *Communication) Reset()                    { *m = Communication{} }
func (m *Communication) String() string            { return proto.CompactTextString(m) }
func (*Communication) ProtoMessage()               {}
func (*Communication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Communication) GetCommsId() string {
	if m != nil {
		return m.CommsId
	}
	return ""
}

func (m *Communication) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Communication) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Communication) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Communication) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

type Journal struct {
	JournalId   string `protobuf:"bytes,1,opt,name=journal_id,json=journalId" json:"journal_id,omitempty"`
	CommsId     string `protobuf:"bytes,2,opt,name=comms_id,json=commsId" json:"comms_id,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Entry       string `protobuf:"bytes,5,opt,name=entry" json:"entry,omitempty"`
	Created     string `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
	Updated     string `protobuf:"bytes,7,opt,name=updated" json:"updated,omitempty"`
}

func (m *Journal) Reset()                    { *m = Journal{} }
func (m *Journal) String() string            { return proto.CompactTextString(m) }
func (*Journal) ProtoMessage()               {}
func (*Journal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Journal) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *Journal) GetCommsId() string {
	if m != nil {
		return m.CommsId
	}
	return ""
}

func (m *Journal) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Journal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Journal) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *Journal) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Journal) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "notify.User")
	proto.RegisterType((*CreateAccountReq)(nil), "notify.CreateAccountReq")
	proto.RegisterType((*CreateAccountResp)(nil), "notify.CreateAccountResp")
	proto.RegisterType((*UserNotification)(nil), "notify.UserNotification")
	proto.RegisterType((*Notification)(nil), "notify.Notification")
	proto.RegisterType((*Communication)(nil), "notify.Communication")
	proto.RegisterType((*Journal)(nil), "notify.Journal")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x72, 0xd3, 0x3c,
	0x14, 0x1d, 0xbb, 0x69, 0x7e, 0x6e, 0xd2, 0x7e, 0xfd, 0x44, 0xa6, 0xe3, 0x66, 0x60, 0xa6, 0x78,
	0x43, 0x37, 0x64, 0x51, 0x58, 0xb0, 0x0d, 0xe5, 0x67, 0xc2, 0xa2, 0x0b, 0x4f, 0xd9, 0x30, 0xc3,
	0x64, 0x1c, 0xfb, 0x26, 0x15, 0x13, 0x4b, 0xaa, 0x24, 0x17, 0x3c, 0x3c, 0x05, 0x6f, 0xc2, 0x53,
	0xf0, 0x20, 0xac, 0x79, 0x08, 0x46, 0xb2, 0x95, 0xd8, 0x49, 0xb3, 0x61, 0xa7, 0x73, 0x8e, 0xac,
	0x73, 0xef, 0xf5, 0x91, 0xe0, 0x48, 0xa1, 0xbc, 0xa7, 0x09, 0x8e, 0x85, 0xe4, 0x9a, 0x93, 0x36,
	0xe3, 0x9a, 0x2e, 0x8a, 0x51, 0x1f, 0x33, 0xa1, 0x8b, 0x92, 0x0c, 0x7f, 0x7a, 0xd0, 0xfa, 0xa8,
	0x50, 0x92, 0xa7, 0x30, 0x10, 0xb7, 0x9c, 0xe1, 0x8c, 0xe5, 0xd9, 0x1c, 0x65, 0xe0, 0x9d, 0x7b,
	0x17, 0xbd, 0xa8, 0x6f, 0xb9, 0x6b, 0x4b, 0x91, 0x11, 0x74, 0x45, 0xac, 0xd4, 0x57, 0x2e, 0xd3,
	0xc0, 0xb7, 0xf2, 0x1a, 0x13, 0x02, 0x2d, 0x16, 0x67, 0x18, 0x1c, 0x58, 0xde, 0xae, 0xcd, 0xfe,
	0x39, 0x95, 0xfa, 0x36, 0x8d, 0x8b, 0xa0, 0x55, 0xee, 0x77, 0xd8, 0x68, 0xf7, 0x28, 0xe9, 0x82,
	0x62, 0x1a, 0x1c, 0x9e, 0x7b, 0x17, 0xdd, 0x68, 0x8d, 0xc9, 0x13, 0x00, 0x85, 0x4a, 0x51, 0xce,
	0x66, 0x34, 0x0d, 0xda, 0xf6, 0xcb, 0x5e, 0xc5, 0x4c, 0xd3, 0xf0, 0x33, 0x9c, 0x5c, 0x49, 0x8c,
	0x35, 0x4e, 0x92, 0x84, 0xe7, 0x4c, 0x47, 0x78, 0x47, 0xce, 0xa1, 0x95, 0xab, 0xaa, 0xea, 0xfe,
	0xe5, 0x60, 0x5c, 0xb6, 0x3a, 0x36, 0x9d, 0x45, 0x56, 0x21, 0xcf, 0xe0, 0x3f, 0x57, 0xec, 0x4c,
	0xa2, 0xc0, 0x58, 0x57, 0x3d, 0x1c, 0x3b, 0x3a, 0xb2, 0x6c, 0xf8, 0x1c, 0xfe, 0xdf, 0x3a, 0x5e,
	0x09, 0x12, 0x40, 0x47, 0xe5, 0x49, 0x82, 0x4a, 0x59, 0x8b, 0x6e, 0xe4, 0x60, 0xf8, 0xc7, 0x83,
	0x13, 0x63, 0x73, 0x6d, 0x1c, 0x69, 0x12, 0x6b, 0xca, 0x99, 0x31, 0x63, 0x35, 0x6c, 0xda, 0x28,
	0xe7, 0x79, 0x5c, 0xa7, 0xa7, 0xe9, 0xce, 0xd4, 0xfd, 0xdd, 0xa9, 0xbf, 0x84, 0x53, 0x86, 0xdf,
	0xf4, 0xac, 0x71, 0xa0, 0xa6, 0xeb, 0x59, 0x0f, 0x8d, 0x5a, 0x77, 0xbf, 0xa1, 0x19, 0x92, 0xc7,
	0xd0, 0x5b, 0x48, 0xbc, 0xcb, 0x91, 0x25, 0x6e, 0xf8, 0x1b, 0x82, 0xbc, 0x82, 0x41, 0xfd, 0x38,
	0xfb, 0x07, 0xfa, 0x97, 0x43, 0x37, 0xb6, 0xfa, 0x69, 0x51, 0x63, 0x67, 0xf8, 0x1d, 0x06, 0xff,
	0xd6, 0xa9, 0x0b, 0x88, 0x5f, 0x0b, 0x08, 0x81, 0x96, 0x2e, 0xc4, 0x3a, 0x34, 0x66, 0x6d, 0x82,
	0xa1, 0x31, 0x13, 0xab, 0x58, 0xa3, 0x0b, 0x8d, 0xc3, 0xe1, 0x0f, 0x0f, 0x8e, 0xae, 0x78, 0x96,
	0xe5, 0xcc, 0xd9, 0x9f, 0x41, 0x37, 0xe1, 0x59, 0xa6, 0x36, 0xbe, 0x1d, 0x8b, 0x4b, 0xc3, 0x85,
	0xe4, 0x99, 0x33, 0x34, 0x6b, 0x72, 0x0c, 0xbe, 0xe6, 0x95, 0x9d, 0xaf, 0xb9, 0xf9, 0xad, 0x19,
	0x2a, 0x15, 0x2f, 0x9d, 0x97, 0x83, 0x0f, 0xf5, 0x75, 0xf8, 0x50, 0x5f, 0xe1, 0x2f, 0x0f, 0x3a,
	0x1f, 0x78, 0x2e, 0x59, 0xbc, 0x32, 0xc1, 0xfd, 0x52, 0x2e, 0x37, 0xf5, 0xf4, 0x2a, 0x66, 0x9a,
	0x36, 0x8a, 0xf5, 0x9b, 0xc5, 0x6e, 0xe7, 0xe0, 0x60, 0x37, 0x07, 0x43, 0x38, 0xd4, 0x54, 0xaf,
	0x5c, 0xa5, 0x25, 0x30, 0x2c, 0x32, 0x2d, 0x8b, 0xaa, 0xba, 0x12, 0x98, 0xbe, 0x12, 0x9b, 0x61,
	0x77, 0x7d, 0x1c, 0x34, 0x4a, 0x2e, 0x52, 0xab, 0x74, 0x4a, 0xa5, 0x82, 0x97, 0xbf, 0x3d, 0xe8,
	0xd9, 0x5f, 0x5b, 0x4c, 0x84, 0x20, 0x6f, 0xe0, 0xa8, 0x71, 0x0b, 0x48, 0xe0, 0xc2, 0xb1, 0x7d,
	0xf7, 0x46, 0x67, 0x7b, 0x14, 0x25, 0xc8, 0x7b, 0x78, 0x34, 0x49, 0xd3, 0x9d, 0xeb, 0x11, 0xd4,
	0xef, 0x67, 0x5d, 0x19, 0x9d, 0x8e, 0x97, 0x9c, 0x2f, 0x57, 0xd5, 0x93, 0x35, 0xcf, 0x17, 0xe3,
	0xb7, 0xe6, 0xb1, 0x22, 0xef, 0x60, 0x78, 0x23, 0xe9, 0x72, 0xd9, 0xdc, 0xae, 0xc8, 0x9e, 0xfd,
	0xfb, 0xce, 0x79, 0xdd, 0xfd, 0xd4, 0x36, 0x8f, 0x22, 0xca, 0x79, 0xdb, 0x2a, 0x2f, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x5c, 0xdc, 0xa4, 0x51, 0x25, 0x05, 0x00, 0x00,
}
